kind: Service
apiVersion: v1

metadata:
    name: nginx-servicio     # fqdn que se da de alta en el DNS de Kubernetes
          # nginx-servicio.ivan

spec:
    type: LoadBalancer #NodePort # ClusterIP # NodePort # LoadBalancer
    ports:
        - port: 8888        # En la IP de balanceo
          targetPort: 80    # El puerto en el contenedor
          nodePort: 31181
    selector:
        aqui-hay: un-nginx

# Para consultar la IP de un servicio?
#$ kubectl describe service/nombre-servicio -n NAMESPACE
#$ kubectl get service/nombre-servicio -n NAMESPACE -o wide