kind: Deployment
apiVersion: apps/v1

metadata:
    name: despliegue-nginx

spec:
    replicas: 5
    # $ kubectl scale desployment/NOMBRE-DEPLOYMENT -n NAMESPACE --replicas=17
    selector:
        matchLabels:
                aqui-hay: un-nginx

    template:
        metadata:
            name: nginxa
            labels:
                aqui-hay: un-nginx
        
        spec:
            containers:
                - # Contenedor nginx
                    name:     contenedor-nginx
                    image:    nginx:latest
