kind: ConfigMap
apiVersion: v1

metadata:
    name: configuracion-nginx

data:

    default.conf: |
        server {
            listen       81;
            listen  [::]:81;
            server_name  localhost;
        
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        
        }
